In [3]:
import pandas as pd
import matplotlib as plt
from bokeh.plotting import figure,show
from bokeh.models import HoverTool
df = pd.read_csv("./car_price.csv")
df

,CarName,carbody,drivewheel,enginelocation,fueltype,aspiration,doornumber,cylindernumber,enginetype,fuelsystem,...,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,alfa-romero giulia,convertible,rwd,front,gas,std,two,four,dohc,mpfi,...,2548,130,3.47,2.68,9.0,111,5000,21,27,13495.0
1,alfa-romero stelvio,convertible,rwd,front,gas,std,two,four,dohc,mpfi,...,2548,130,3.47,2.68,9.0,111,5000,21,27,16500.0
2,alfa-romero Quadrifoglio,hatchback,rwd,front,gas,std,two,six,ohcv,mpfi,...,2823,152,2.68,3.47,9.0,154,5000,19,26,16500.0
3,audi 100 ls,sedan,fwd,front,gas,std,four,four,ohc,mpfi,...,2337,109,3.19,3.40,10.0,102,5500,24,30,13950.0
4,audi 100ls,sedan,4wd,front,gas,std,four,five,ohc,mpfi,...,2824,136,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,bmw x3,sedan,rwd,front,gas,std,four,six,ohc,mpfi,...,2765,164,3.31,3.19,9.0,121,4250,21,28,21105.0
206,mitsubishi g4,hatchback,fwd,front,gas,std,two,four,ohc,2bbl,...,2328,122,3.35,3.46,8.5,88,5000,25,32,8499.0
207,peugeot 304,sedan,rwd,front,diesel,turbo,four,four,l,idi,...,3197,152,3.70,3.52,21.0,95,4150,28,33,13200.0
208,peugeot 504 (sw),wagon,rwd,front,gas,std,four,four,l,mpfi,...,3230,120,3.46,3.19,8.4,97,5000,19,24,12440.0
209,peugeot 504,wagon,rwd,front,diesel,turbo,four,four,l,idi,...,3430,152,3.70,3.52,21.0,95,4150,25,25,13860.0

In [4]:
#checking out the datatype
main = df[["CarName", "enginetype", "price", "cylindernumber", "horsepower"]]
main

                      CarName enginetype    price cylindernumber  horsepower
0          alfa-romero giulia       dohc  13495.0           four         111
1         alfa-romero stelvio       dohc  16500.0           four         111
2    alfa-romero Quadrifoglio       ohcv  16500.0            six         154
3                 audi 100 ls        ohc  13950.0           four         102
4                  audi 100ls        ohc  17450.0           five         115
..                        ...        ...      ...            ...         ...
205                    bmw x3        ohc  21105.0            six         121
206             mitsubishi g4        ohc   8499.0           four          88
207               peugeot 304          l  13200.0           four          95
208          peugeot 504 (sw)          l  12440.0           four          97
209               peugeot 504          l  13860.0           four          95

[210 rows x 5 columns]

In [5]:
mean_price = df["price"].mean()
mean_price

13289.66508095238

In [6]:
main[main["cylindernumber"].isin(["four", "five"])]

                 CarName enginetype    price cylindernumber  horsepower
0     alfa-romero giulia       dohc  13495.0           four         111
1    alfa-romero stelvio       dohc  16500.0           four         111
3            audi 100 ls        ohc  13950.0           four         102
4             audi 100ls        ohc  17450.0           five         115
5               audi fox        ohc  15250.0           five         110
..                   ...        ...      ...            ...         ...
204          volvo 264gl        ohc  22625.0           four         114
206        mitsubishi g4        ohc   8499.0           four          88
207          peugeot 304          l  13200.0           four          95
208     peugeot 504 (sw)          l  12440.0           four          97
209          peugeot 504          l  13860.0           four          95

[174 rows x 5 columns]

In [7]:
ab_av = main.loc[main["price"] > mean_price, ["CarName", "enginetype", "cylindernumber", "horsepower", "price"]]
ab_av

                      CarName enginetype cylindernumber  horsepower    price
0          alfa-romero giulia       dohc           four         111  13495.0
1         alfa-romero stelvio       dohc           four         111  16500.0
2    alfa-romero Quadrifoglio       ohcv            six         154  16500.0
3                 audi 100 ls        ohc           four         102  13950.0
4                  audi 100ls        ohc           five         115  17450.0
..                        ...        ...            ...         ...      ...
202               volvo 244dl       ohcv            six         134  21485.0
203                 volvo 246        ohc            six         106  22470.0
204               volvo 264gl        ohc           four         114  22625.0
205                    bmw x3        ohc            six         121  21105.0
209               peugeot 504          l           four          95  13860.0

[78 rows x 5 columns]

In [8]:
ab_av["diff"] = ab_av["price"] - mean_price
ab_av

,CarName,enginetype,cylindernumber,horsepower,price,diff
0,alfa-romero giulia,dohc,four,111,13495.0,205.334919
1,alfa-romero stelvio,dohc,four,111,16500.0,3210.334919
2,alfa-romero Quadrifoglio,ohcv,six,154,16500.0,3210.334919
3,audi 100 ls,ohc,four,102,13950.0,660.334919
4,audi 100ls,ohc,five,115,17450.0,4160.334919
...,...,...,...,...,...,...
202,volvo 244dl,ohcv,six,134,21485.0,8195.334919
203,volvo 246,ohc,six,106,22470.0,9180.334919
204,volvo 264gl,ohc,four,114,22625.0,9335.334919
205,bmw x3,ohc,six,121,21105.0,7815.334919
209,peugeot 504,l,four,95,13860.0,570.334919

In [9]:
ab_av.groupby("enginetype").mean()

/var/folders/rx/458dk2h51yl475xpmg4bpdzc0000gn/T/ipykernel_1186/1183936986.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  ab_av.groupby("enginetype").mean()

            horsepower         price          diff
enginetype
dohc        152.800000  19856.100000   6566.434919
dohcv       288.000000  31400.500000  18110.834919
l           100.444444  16300.000000   3010.334919
ohc         126.125000  20319.429175   7029.764094
ohcf        207.000000  34528.000000  21238.334919
ohcv        169.538462  25098.384615  11808.719534
rotor       118.000000  14645.000000   1355.334919

In [16]:
TOOLTIP = HoverTool(tooltips = [
    ("index", "$index"),
    ("(horsepower, price)", "(@horsepower, @price)"),
    ("car name", "@CarName")
])

p = figure(title="car analysis", x_axis_label = "price", y_axis_label="horsepower", width=700, height=700, tools=[TOOLTIP])

p.circle("price", "horsepower", size=5, source=main)
show(p)

ValueError: failed to validate HoverTool(id='p1350', ...).tooltips: expected an element of either Null, Instance(Template), String or List(Tuple(String, String)), got [('index', '$index'), (('horsepower', 'price'), ('@horsepower', '@price')), ('car name', '@CarName')]

In [ ]:
main.loc[main["price"] < mean_price, ["CarName", "enginetype", "cylindernumber", "horsepower"]]

                   CarName enginetype cylindernumber  horsepower
18        chevrolet impala          l          three          48
19   chevrolet monte carlo        ohc           four          70
20     chevrolet vega 2300        ohc           four          70
21           dodge rampage        ohc           four          68
22     dodge challenger se        ohc           four          68
..                     ...        ...            ...         ...
193      volkswagen dasher        ohc           four          88
194        volvo 145e (sw)        ohc           four         114
206          mitsubishi g4        ohc           four          88
207            peugeot 304          l           four          95
208       peugeot 504 (sw)          l           four          97

[132 rows x 4 columns]